env: "local"    # local, dev, prod - окружение в котором запускается приложение
storage_path: "./storage/storage.db"  # путь к базе данных
http_server:
  address: "localhost:8081"
  timeout: 4s   # время на чтение запроса и отправку ответа (обработка неограничена по времени)
  idle_timeout: 60s  # время жизни соединения с клиентом